### ISSUE TITLE
HtmlInputElement: Cannot use events

### ISSUE THREAD

**Issue by nabak9** [CyberPhoenix90/aurum-seed-typescript#1]
Trying to get the target value of an event doesn't compile.

`InputProps` use `DataDrain<InputEvent>` on the `onChange` function.
If I dig deeper, I get to the lib.dom.d.ts file and find the following hierarchy: InputEvent -> UIEvent -> Event -> which uses EventTarget on the `target` attribute.

Only thing the stacktrace mentions is the line itself:
`Property 'value' does not exist on type 'EventTarget'` .

Try out this simple example code to reproduce:
```typescript
let yourDataSource = new DataSource(undefined);

Aurum.attach(<div>
  <input initialValue={yourDataSource.value} onChange={(e) => yourDataSource.update(e.target.value)}/> 
</div>, document.body);

```

**Comment by CyberPhoenix90** [comment]
That has nothing to do with Aurum. lib.dom.d.ts is from typescript you can get the same problem with just vanilla typescript like this:

let a: HTMLInputElement;
a.addEventListener('change', (e) => {
	console.log(e.target.value);
});
